disenchant-xp: 100
split-xp: 50

xp-mode: XP # XP or LEVELS

prevent-curses: true

sounds:
  enabled: true
  disenchant: block.enchantment_table.use
  split: entity.experience_orb.pickup

auraskills:
  enabled: true

  xp:
    disenchant:
      per-enchant: 4.0

    split: 2.5